// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/gen3Client (interfaces: Gen3Interface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_gen3interface.go -package=mocks github.com/calypr/data-client/client/gen3Client Gen3Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	api "github.com/calypr/data-client/client/api"
	conf "github.com/calypr/data-client/client/conf"
	logs "github.com/calypr/data-client/client/logs"
	req "github.com/calypr/data-client/client/request"
	gomock "go.uber.org/mock/gomock"
)

// MockGen3Interface is a mock of Gen3Interface interface.
type MockGen3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockGen3InterfaceMockRecorder
	isgomock struct{}
}

// MockGen3InterfaceMockRecorder is the mock recorder for MockGen3Interface.
type MockGen3InterfaceMockRecorder struct {
	mock *MockGen3Interface
}

// NewMockGen3Interface creates a new mock instance.
func NewMockGen3Interface(ctrl *gomock.Controller) *MockGen3Interface {
	mock := &MockGen3Interface{ctrl: ctrl}
	mock.recorder = &MockGen3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGen3Interface) EXPECT() *MockGen3InterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method.
func (m *MockGen3Interface) CheckForShepherdAPI(cred *conf.Credential) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForShepherdAPI", cred)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI.
func (mr *MockGen3InterfaceMockRecorder) CheckForShepherdAPI(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockGen3Interface)(nil).CheckForShepherdAPI), cred)
}

// CheckPrivileges mocks base method.
func (m *MockGen3Interface) CheckPrivileges(cred *conf.Credential) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivileges", cred)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPrivileges indicates an expected call of CheckPrivileges.
func (mr *MockGen3InterfaceMockRecorder) CheckPrivileges(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockGen3Interface)(nil).CheckPrivileges), cred)
}

// DeleteRecord mocks base method.
func (m *MockGen3Interface) DeleteRecord(profileConfig *conf.Credential, guid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", profileConfig, guid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockGen3InterfaceMockRecorder) DeleteRecord(profileConfig, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockGen3Interface)(nil).DeleteRecord), profileConfig, guid)
}

// DoAuthenticatedRequest mocks base method.
func (m *MockGen3Interface) DoAuthenticatedRequest(cred *conf.Credential, request *req.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAuthenticatedRequest", cred, request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoAuthenticatedRequest indicates an expected call of DoAuthenticatedRequest.
func (mr *MockGen3InterfaceMockRecorder) DoAuthenticatedRequest(cred, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAuthenticatedRequest", reflect.TypeOf((*MockGen3Interface)(nil).DoAuthenticatedRequest), cred, request)
}

// ExportCredential mocks base method.
func (m *MockGen3Interface) ExportCredential(cred *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportCredential", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportCredential indicates an expected call of ExportCredential.
func (mr *MockGen3InterfaceMockRecorder) ExportCredential(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCredential", reflect.TypeOf((*MockGen3Interface)(nil).ExportCredential), cred)
}

// GetCredential mocks base method.
func (m *MockGen3Interface) GetCredential() *conf.Credential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential")
	ret0, _ := ret[0].(*conf.Credential)
	return ret0
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockGen3InterfaceMockRecorder) GetCredential() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockGen3Interface)(nil).GetCredential))
}

// Logger mocks base method.
func (m *MockGen3Interface) Logger() *logs.TeeLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*logs.TeeLogger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockGen3InterfaceMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockGen3Interface)(nil).Logger))
}

// NewAccessToken mocks base method.
func (m *MockGen3Interface) NewAccessToken(profileConfig *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAccessToken", profileConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewAccessToken indicates an expected call of NewAccessToken.
func (mr *MockGen3InterfaceMockRecorder) NewAccessToken(profileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAccessToken", reflect.TypeOf((*MockGen3Interface)(nil).NewAccessToken), profileConfig)
}

// ParseFenceURLResponse mocks base method.
func (m *MockGen3Interface) ParseFenceURLResponse(resp *http.Response) (api.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFenceURLResponse", resp)
	ret0, _ := ret[0].(api.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFenceURLResponse indicates an expected call of ParseFenceURLResponse.
func (mr *MockGen3InterfaceMockRecorder) ParseFenceURLResponse(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFenceURLResponse", reflect.TypeOf((*MockGen3Interface)(nil).ParseFenceURLResponse), resp)
}
