// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/api (interfaces: FunctionInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_functions.go -package=mocks github.com/calypr/data-client/client/api FunctionInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	api "github.com/calypr/data-client/client/api"
	conf "github.com/calypr/data-client/client/conf"
	req "github.com/calypr/data-client/client/request"
	gomock "go.uber.org/mock/gomock"
)

// MockFunctionInterface is a mock of FunctionInterface interface.
type MockFunctionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionInterfaceMockRecorder
	isgomock struct{}
}

// MockFunctionInterfaceMockRecorder is the mock recorder for MockFunctionInterface.
type MockFunctionInterfaceMockRecorder struct {
	mock *MockFunctionInterface
}

// NewMockFunctionInterface creates a new mock instance.
func NewMockFunctionInterface(ctrl *gomock.Controller) *MockFunctionInterface {
	mock := &MockFunctionInterface{ctrl: ctrl}
	mock.recorder = &MockFunctionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunctionInterface) EXPECT() *MockFunctionInterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method.
func (m *MockFunctionInterface) CheckForShepherdAPI(cred *conf.Credential) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForShepherdAPI", cred)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI.
func (mr *MockFunctionInterfaceMockRecorder) CheckForShepherdAPI(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockFunctionInterface)(nil).CheckForShepherdAPI), cred)
}

// CheckPrivileges mocks base method.
func (m *MockFunctionInterface) CheckPrivileges(cred *conf.Credential) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivileges", cred)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPrivileges indicates an expected call of CheckPrivileges.
func (mr *MockFunctionInterfaceMockRecorder) CheckPrivileges(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockFunctionInterface)(nil).CheckPrivileges), cred)
}

// DeleteRecord mocks base method.
func (m *MockFunctionInterface) DeleteRecord(profileConfig *conf.Credential, guid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", profileConfig, guid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockFunctionInterfaceMockRecorder) DeleteRecord(profileConfig, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockFunctionInterface)(nil).DeleteRecord), profileConfig, guid)
}

// DoAuthenticatedRequest mocks base method.
func (m *MockFunctionInterface) DoAuthenticatedRequest(cred *conf.Credential, request *req.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAuthenticatedRequest", cred, request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoAuthenticatedRequest indicates an expected call of DoAuthenticatedRequest.
func (mr *MockFunctionInterfaceMockRecorder) DoAuthenticatedRequest(cred, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAuthenticatedRequest", reflect.TypeOf((*MockFunctionInterface)(nil).DoAuthenticatedRequest), cred, request)
}

// ExportCredential mocks base method.
func (m *MockFunctionInterface) ExportCredential(cred *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportCredential", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportCredential indicates an expected call of ExportCredential.
func (mr *MockFunctionInterfaceMockRecorder) ExportCredential(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCredential", reflect.TypeOf((*MockFunctionInterface)(nil).ExportCredential), cred)
}

// ParseFenceURLResponse mocks base method.
func (m *MockFunctionInterface) ParseFenceURLResponse(resp *http.Response) (api.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFenceURLResponse", resp)
	ret0, _ := ret[0].(api.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFenceURLResponse indicates an expected call of ParseFenceURLResponse.
func (mr *MockFunctionInterfaceMockRecorder) ParseFenceURLResponse(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFenceURLResponse", reflect.TypeOf((*MockFunctionInterface)(nil).ParseFenceURLResponse), resp)
}
