// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/jwt (interfaces: FunctionInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_functions.go -package=mocks github.com/calypr/data-client/client/jwt FunctionInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	url "net/url"
	reflect "reflect"

	jwt "github.com/calypr/data-client/client/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockFunctionInterface is a mock of FunctionInterface interface.
type MockFunctionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFunctionInterfaceMockRecorder
	isgomock struct{}
}

// MockFunctionInterfaceMockRecorder is the mock recorder for MockFunctionInterface.
type MockFunctionInterfaceMockRecorder struct {
	mock *MockFunctionInterface
}

// NewMockFunctionInterface creates a new mock instance.
func NewMockFunctionInterface(ctrl *gomock.Controller) *MockFunctionInterface {
	mock := &MockFunctionInterface{ctrl: ctrl}
	mock.recorder = &MockFunctionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFunctionInterface) EXPECT() *MockFunctionInterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method.
func (m *MockFunctionInterface) CheckForShepherdAPI(profileConfig *jwt.Credential) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForShepherdAPI", profileConfig)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI.
func (mr *MockFunctionInterfaceMockRecorder) CheckForShepherdAPI(profileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockFunctionInterface)(nil).CheckForShepherdAPI), profileConfig)
}

// CheckPrivileges mocks base method.
func (m *MockFunctionInterface) CheckPrivileges(profileConfig *jwt.Credential) (string, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivileges", profileConfig)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPrivileges indicates an expected call of CheckPrivileges.
func (mr *MockFunctionInterfaceMockRecorder) CheckPrivileges(profileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockFunctionInterface)(nil).CheckPrivileges), profileConfig)
}

// DoRequestWithSignedHeader mocks base method.
func (m *MockFunctionInterface) DoRequestWithSignedHeader(profileConfig *jwt.Credential, endpointPostPrefix, contentType string, bodyBytes []byte) (jwt.JsonMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoRequestWithSignedHeader", profileConfig, endpointPostPrefix, contentType, bodyBytes)
	ret0, _ := ret[0].(jwt.JsonMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoRequestWithSignedHeader indicates an expected call of DoRequestWithSignedHeader.
func (mr *MockFunctionInterfaceMockRecorder) DoRequestWithSignedHeader(profileConfig, endpointPostPrefix, contentType, bodyBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequestWithSignedHeader", reflect.TypeOf((*MockFunctionInterface)(nil).DoRequestWithSignedHeader), profileConfig, endpointPostPrefix, contentType, bodyBytes)
}

// GetHost mocks base method.
func (m *MockFunctionInterface) GetHost(profileConfig *jwt.Credential) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost", profileConfig)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost.
func (mr *MockFunctionInterfaceMockRecorder) GetHost(profileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockFunctionInterface)(nil).GetHost), profileConfig)
}

// GetResponse mocks base method.
func (m *MockFunctionInterface) GetResponse(profileConfig *jwt.Credential, endpointPostPrefix, method, contentType string, bodyBytes []byte) (string, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponse", profileConfig, endpointPostPrefix, method, contentType, bodyBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetResponse indicates an expected call of GetResponse.
func (mr *MockFunctionInterfaceMockRecorder) GetResponse(profileConfig, endpointPostPrefix, method, contentType, bodyBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponse", reflect.TypeOf((*MockFunctionInterface)(nil).GetResponse), profileConfig, endpointPostPrefix, method, contentType, bodyBytes)
}

// ParseFenceURLResponse mocks base method.
func (m *MockFunctionInterface) ParseFenceURLResponse(resp *http.Response) (jwt.JsonMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFenceURLResponse", resp)
	ret0, _ := ret[0].(jwt.JsonMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFenceURLResponse indicates an expected call of ParseFenceURLResponse.
func (mr *MockFunctionInterfaceMockRecorder) ParseFenceURLResponse(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFenceURLResponse", reflect.TypeOf((*MockFunctionInterface)(nil).ParseFenceURLResponse), resp)
}
