// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/request (interfaces: RequestInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_request.go -package=mocks github.com/calypr/data-client/client/request RequestInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	http "net/http"
	reflect "reflect"

	conf "github.com/calypr/data-client/client/conf"
	logs "github.com/calypr/data-client/client/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestInterface is a mock of RequestInterface interface.
type MockRequestInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRequestInterfaceMockRecorder
	isgomock struct{}
}

// MockRequestInterfaceMockRecorder is the mock recorder for MockRequestInterface.
type MockRequestInterfaceMockRecorder struct {
	mock *MockRequestInterface
}

// NewMockRequestInterface creates a new mock instance.
func NewMockRequestInterface(ctrl *gomock.Controller) *MockRequestInterface {
	mock := &MockRequestInterface{ctrl: ctrl}
	mock.recorder = &MockRequestInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestInterface) EXPECT() *MockRequestInterfaceMockRecorder {
	return m.recorder
}

// Logger mocks base method.
func (m *MockRequestInterface) Logger() logs.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(logs.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockRequestInterfaceMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockRequestInterface)(nil).Logger))
}

// MakeARequest mocks base method.
func (m *MockRequestInterface) MakeARequest(method, apiEndpoint, accessToken, contentType string, headers map[string]string, body *bytes.Buffer, noTimeout bool) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeARequest", method, apiEndpoint, accessToken, contentType, headers, body, noTimeout)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeARequest indicates an expected call of MakeARequest.
func (mr *MockRequestInterfaceMockRecorder) MakeARequest(method, apiEndpoint, accessToken, contentType, headers, body, noTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeARequest", reflect.TypeOf((*MockRequestInterface)(nil).MakeARequest), method, apiEndpoint, accessToken, contentType, headers, body, noTimeout)
}

// RequestNewAccessToken mocks base method.
func (m *MockRequestInterface) RequestNewAccessToken(accessTokenEndpoint string, profileConfig *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestNewAccessToken", accessTokenEndpoint, profileConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestNewAccessToken indicates an expected call of RequestNewAccessToken.
func (mr *MockRequestInterfaceMockRecorder) RequestNewAccessToken(accessTokenEndpoint, profileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestNewAccessToken", reflect.TypeOf((*MockRequestInterface)(nil).RequestNewAccessToken), accessTokenEndpoint, profileConfig)
}
