// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/gen3Client (interfaces: Gen3Interface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_gen3interface.go -package=mocks github.com/calypr/data-client/client/gen3Client Gen3Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	http "net/http"
	url "net/url"
	reflect "reflect"

	api "github.com/calypr/data-client/client/api"
	conf "github.com/calypr/data-client/client/conf"
	logs "github.com/calypr/data-client/client/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockGen3Interface is a mock of Gen3Interface interface.
type MockGen3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockGen3InterfaceMockRecorder
	isgomock struct{}
}

// MockGen3InterfaceMockRecorder is the mock recorder for MockGen3Interface.
type MockGen3InterfaceMockRecorder struct {
	mock *MockGen3Interface
}

// NewMockGen3Interface creates a new mock instance.
func NewMockGen3Interface(ctrl *gomock.Controller) *MockGen3Interface {
	mock := &MockGen3Interface{ctrl: ctrl}
	mock.recorder = &MockGen3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGen3Interface) EXPECT() *MockGen3InterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method.
func (m *MockGen3Interface) CheckForShepherdAPI() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForShepherdAPI")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI.
func (mr *MockGen3InterfaceMockRecorder) CheckForShepherdAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockGen3Interface)(nil).CheckForShepherdAPI))
}

// CheckPrivileges mocks base method.
func (m *MockGen3Interface) CheckPrivileges() (string, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivileges")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPrivileges indicates an expected call of CheckPrivileges.
func (mr *MockGen3InterfaceMockRecorder) CheckPrivileges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockGen3Interface)(nil).CheckPrivileges))
}

// DeleteRecord mocks base method.
func (m *MockGen3Interface) DeleteRecord(guid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", guid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockGen3InterfaceMockRecorder) DeleteRecord(guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockGen3Interface)(nil).DeleteRecord), guid)
}

// DoRequestWithSignedHeader mocks base method.
func (m *MockGen3Interface) DoRequestWithSignedHeader(endpointPostPrefix, contentType string, bodyBytes []byte) (api.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoRequestWithSignedHeader", endpointPostPrefix, contentType, bodyBytes)
	ret0, _ := ret[0].(api.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoRequestWithSignedHeader indicates an expected call of DoRequestWithSignedHeader.
func (mr *MockGen3InterfaceMockRecorder) DoRequestWithSignedHeader(endpointPostPrefix, contentType, bodyBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequestWithSignedHeader", reflect.TypeOf((*MockGen3Interface)(nil).DoRequestWithSignedHeader), endpointPostPrefix, contentType, bodyBytes)
}

// GetCredential mocks base method.
func (m *MockGen3Interface) GetCredential() *conf.Credential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential")
	ret0, _ := ret[0].(*conf.Credential)
	return ret0
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockGen3InterfaceMockRecorder) GetCredential() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockGen3Interface)(nil).GetCredential))
}

// GetHost mocks base method.
func (m *MockGen3Interface) GetHost() (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost.
func (mr *MockGen3InterfaceMockRecorder) GetHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockGen3Interface)(nil).GetHost))
}

// GetResponse mocks base method.
func (m *MockGen3Interface) GetResponse(endpointPostPrefix, method, contentType string, bodyBytes []byte) (string, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponse", endpointPostPrefix, method, contentType, bodyBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetResponse indicates an expected call of GetResponse.
func (mr *MockGen3InterfaceMockRecorder) GetResponse(endpointPostPrefix, method, contentType, bodyBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponse", reflect.TypeOf((*MockGen3Interface)(nil).GetResponse), endpointPostPrefix, method, contentType, bodyBytes)
}

// Logger mocks base method.
func (m *MockGen3Interface) Logger() *logs.TeeLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*logs.TeeLogger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockGen3InterfaceMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockGen3Interface)(nil).Logger))
}

// MakeARequest mocks base method.
func (m *MockGen3Interface) MakeARequest(method, apiEndpoint, accessToken, contentType string, headers map[string]string, body *bytes.Buffer, noTimeout bool) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeARequest", method, apiEndpoint, accessToken, contentType, headers, body, noTimeout)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeARequest indicates an expected call of MakeARequest.
func (mr *MockGen3InterfaceMockRecorder) MakeARequest(method, apiEndpoint, accessToken, contentType, headers, body, noTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeARequest", reflect.TypeOf((*MockGen3Interface)(nil).MakeARequest), method, apiEndpoint, accessToken, contentType, headers, body, noTimeout)
}
