// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/g3cmd (interfaces: Gen3Interface)

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	http "net/http"
	url "net/url"
	reflect "reflect"

	jwt "github.com/calypr/data-client/client/jwt"
	"github.com/calypr/data-client/client/logs"
	gomock "github.com/golang/mock/gomock"
)

// MockGen3Interface is a mock of Gen3Interface interface
type MockGen3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockGen3InterfaceMockRecorder
}

// MockGen3InterfaceMockRecorder is the mock recorder for MockGen3Interface
type MockGen3InterfaceMockRecorder struct {
	mock *MockGen3Interface
}

// NewMockGen3Interface creates a new mock instance
func NewMockGen3Interface(ctrl *gomock.Controller) *MockGen3Interface {
	mock := &MockGen3Interface{ctrl: ctrl}
	mock.recorder = &MockGen3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGen3Interface) EXPECT() *MockGen3InterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method
func (m *MockGen3Interface) CheckForShepherdAPI() (bool, error) {
	ret := m.ctrl.Call(m, "CheckForShepherdAPI")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI
func (mr *MockGen3InterfaceMockRecorder) CheckForShepherdAPI() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockGen3Interface)(nil).CheckForShepherdAPI))
}

// CheckPrivileges mocks base method
func (m *MockGen3Interface) CheckPrivileges() (string, map[string]any, error) {
	ret := m.ctrl.Call(m, "CheckPrivileges")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPrivileges indicates an expected call of CheckPrivileges
func (mr *MockGen3InterfaceMockRecorder) CheckPrivileges() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockGen3Interface)(nil).CheckPrivileges))
}

// DoRequestWithSignedHeader mocks base method
func (m *MockGen3Interface) DoRequestWithSignedHeader(arg1, arg2 string, arg3 []byte) (jwt.JsonMessage, error) {
	ret := m.ctrl.Call(m, "DoRequestWithSignedHeader", arg1, arg2, arg3)
	ret0, _ := ret[0].(jwt.JsonMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoRequestWithSignedHeader indicates an expected call of DoRequestWithSignedHeader
func (mr *MockGen3InterfaceMockRecorder) DoRequestWithSignedHeader(arg1, arg2, arg3 any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequestWithSignedHeader", reflect.TypeOf((*MockGen3Interface)(nil).DoRequestWithSignedHeader), arg1, arg2, arg3)
}

// GetHost mocks base method
func (m *MockGen3Interface) GetHost() (*url.URL, error) {
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost
func (mr *MockGen3InterfaceMockRecorder) GetHost() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockGen3Interface)(nil).GetHost))
}

// GetResponse mocks base method
func (m *MockGen3Interface) GetResponse(arg1, arg2, arg3 string, arg4 []byte) (string, *http.Response, error) {
	ret := m.ctrl.Call(m, "GetResponse", arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetResponse indicates an expected call of GetResponse
func (mr *MockGen3InterfaceMockRecorder) GetResponse(arg1, arg2, arg3, arg4 any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponse", reflect.TypeOf((*MockGen3Interface)(nil).GetResponse), arg1, arg2, arg3, arg4)
}

// GetCredential mocks base method
func (m *MockGen3Interface) GetCredential() *jwt.Credential {
	ret := m.ctrl.Call(m, "GetCredential")
	ret0, _ := ret[0].(*jwt.Credential)
	return ret0
}

// GetCredential indicates an expected call of GetCredential
func (mr *MockGen3InterfaceMockRecorder) GetCredential() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockGen3Interface)(nil).GetCredential))
}

// DeleteRecord mocks base method
func (m *MockGen3Interface) DeleteRecord(arg0 string) (string, error) {
	ret := m.ctrl.Call(m, "DeleteRecord", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecord indicates an expected call of DeleteRecord
func (mr *MockGen3InterfaceMockRecorder) DeleteRecord(arg0 any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockGen3Interface)(nil).DeleteRecord), arg0)
}

// MakeARequest mocks base method
func (m *MockGen3Interface) MakeARequest(arg0, arg1, arg2, arg3 string, arg4 map[string]string, arg5 *bytes.Buffer, arg6 bool) (*http.Response, error) {
	ret := m.ctrl.Call(m, "MakeARequest", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (m *MockGen3Interface) Logger() logs.Logger {
	return logs.New("test")
}

// MakeARequest indicates an expected call of MakeARequest
func (mr *MockGen3InterfaceMockRecorder) MakeARequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeARequest", reflect.TypeOf((*MockGen3Interface)(nil).MakeARequest), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
