// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/client/jwt (interfaces: ConfigureInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_configure.go -package=mocks github.com/calypr/data-client/client/jwt ConfigureInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	url "net/url"
	reflect "reflect"

	jwt "github.com/calypr/data-client/client/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigureInterface is a mock of ConfigureInterface interface.
type MockConfigureInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigureInterfaceMockRecorder
	isgomock struct{}
}

// MockConfigureInterfaceMockRecorder is the mock recorder for MockConfigureInterface.
type MockConfigureInterfaceMockRecorder struct {
	mock *MockConfigureInterface
}

// NewMockConfigureInterface creates a new mock instance.
func NewMockConfigureInterface(ctrl *gomock.Controller) *MockConfigureInterface {
	mock := &MockConfigureInterface{ctrl: ctrl}
	mock.recorder = &MockConfigureInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigureInterface) EXPECT() *MockConfigureInterfaceMockRecorder {
	return m.recorder
}

// GetConfigPath mocks base method.
func (m *MockConfigureInterface) GetConfigPath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockConfigureInterfaceMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockConfigureInterface)(nil).GetConfigPath))
}

// IsValidCredential mocks base method.
func (m *MockConfigureInterface) IsValidCredential(arg0 jwt.Credential) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidCredential", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidCredential indicates an expected call of IsValidCredential.
func (mr *MockConfigureInterfaceMockRecorder) IsValidCredential(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidCredential", reflect.TypeOf((*MockConfigureInterface)(nil).IsValidCredential), arg0)
}

// ParseConfig mocks base method.
func (m *MockConfigureInterface) ParseConfig(profile string) (jwt.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConfig", profile)
	ret0, _ := ret[0].(jwt.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConfig indicates an expected call of ParseConfig.
func (mr *MockConfigureInterfaceMockRecorder) ParseConfig(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfig", reflect.TypeOf((*MockConfigureInterface)(nil).ParseConfig), profile)
}

// ParseKeyValue mocks base method.
func (m *MockConfigureInterface) ParseKeyValue(str, expr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseKeyValue", str, expr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseKeyValue indicates an expected call of ParseKeyValue.
func (mr *MockConfigureInterfaceMockRecorder) ParseKeyValue(str, expr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseKeyValue", reflect.TypeOf((*MockConfigureInterface)(nil).ParseKeyValue), str, expr)
}

// ReadFile mocks base method.
func (m *MockConfigureInterface) ReadFile(arg0, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockConfigureInterfaceMockRecorder) ReadFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockConfigureInterface)(nil).ReadFile), arg0, arg1)
}

// UpdateConfigFile mocks base method.
func (m *MockConfigureInterface) UpdateConfigFile(arg0 jwt.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigFile indicates an expected call of UpdateConfigFile.
func (mr *MockConfigureInterfaceMockRecorder) UpdateConfigFile(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigFile", reflect.TypeOf((*MockConfigureInterface)(nil).UpdateConfigFile), arg0)
}

// ValidateUrl mocks base method.
func (m *MockConfigureInterface) ValidateUrl(arg0 string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUrl", arg0)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUrl indicates an expected call of ValidateUrl.
func (mr *MockConfigureInterfaceMockRecorder) ValidateUrl(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUrl", reflect.TypeOf((*MockConfigureInterface)(nil).ValidateUrl), arg0)
}
