// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/drs (interfaces: Client)

package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	drs "github.com/calypr/data-client/drs"
	hash "github.com/calypr/data-client/hash"
	request "github.com/calypr/data-client/request"
	gomock "go.uber.org/mock/gomock"
)

// MockDrsClient is a mock of Client interface.
type MockDrsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDrsClientMockRecorder
}

// MockDrsClientMockRecorder is the mock recorder for MockDrsClient.
type MockDrsClientMockRecorder struct {
	mock *MockDrsClient
}

// NewMockDrsClient creates a new mock instance.
func NewMockDrsClient(ctrl *gomock.Controller) *MockDrsClient {
	mock := &MockDrsClient{ctrl: ctrl}
	mock.recorder = &MockDrsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrsClient) EXPECT() *MockDrsClientMockRecorder {
	return m.recorder
}

func (m *MockDrsClient) BatchGetObjectsByHash(ctx context.Context, hashes []string) (map[string][]drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetObjectsByHash", ctx, hashes)
	ret0, _ := ret[0].(map[string][]drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) BatchGetObjectsByHash(ctx, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetObjectsByHash", reflect.TypeOf((*MockDrsClient)(nil).BatchGetObjectsByHash), ctx, hashes)
}

func (m *MockDrsClient) DeleteRecord(ctx context.Context, did string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", ctx, did)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDrsClientMockRecorder) DeleteRecord(ctx, did any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockDrsClient)(nil).DeleteRecord), ctx, did)
}

func (m *MockDrsClient) GetDownloadURL(ctx context.Context, id string, accessType string) (*drs.AccessURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadURL", ctx, id, accessType)
	ret0, _ := ret[0].(*drs.AccessURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) GetDownloadURL(ctx, id, accessType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadURL", reflect.TypeOf((*MockDrsClient)(nil).GetDownloadURL), ctx, id, accessType)
}

func (m *MockDrsClient) GetObject(ctx context.Context, id string) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, id)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) GetObject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockDrsClient)(nil).GetObject), ctx, id)
}

func (m *MockDrsClient) GetObjectByHash(ctx context.Context, checksum *hash.Checksum) ([]drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectByHash", ctx, checksum)
	ret0, _ := ret[0].([]drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) GetObjectByHash(ctx, checksum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectByHash", reflect.TypeOf((*MockDrsClient)(nil).GetObjectByHash), ctx, checksum)
}

func (m *MockDrsClient) RegisterRecord(ctx context.Context, record *drs.DRSObject) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRecord", ctx, record)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) RegisterRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRecord", reflect.TypeOf((*MockDrsClient)(nil).RegisterRecord), ctx, record)
}

func (m *MockDrsClient) UpdateRecord(ctx context.Context, updateInfo *drs.DRSObject, did string) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecord", ctx, updateInfo, did)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) UpdateRecord(ctx, updateInfo, did any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecord", reflect.TypeOf((*MockDrsClient)(nil).UpdateRecord), ctx, updateInfo, did)
}

func (m *MockDrsClient) UpsertRecord(ctx context.Context, url string, sha256 string, fileSize int64, projectId string) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRecord", ctx, url, sha256, fileSize, projectId)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) UpsertRecord(ctx, url, sha256, fileSize, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRecord", reflect.TypeOf((*MockDrsClient)(nil).UpsertRecord), ctx, url, sha256, fileSize, projectId)
}

func (m *MockDrsClient) Do(ctx context.Context, req *request.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDrsClient)(nil).Do), ctx, req)
}

func (m *MockDrsClient) RegisterRecords(ctx context.Context, records []*drs.DRSObject) ([]*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRecords", ctx, records)
	ret0, _ := ret[0].([]*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) RegisterRecords(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRecords", reflect.TypeOf((*MockDrsClient)(nil).RegisterRecords), ctx, records)
}

func (m *MockDrsClient) ListObjects(ctx context.Context) (chan drs.DRSObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx)
	ret0, _ := ret[0].(chan drs.DRSObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDrsClientMockRecorder) ListObjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockDrsClient)(nil).ListObjects), ctx)
}

func (m *MockDrsClient) New(method, url string) *request.RequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", method, url)
	ret0, _ := ret[0].(*request.RequestBuilder)
	return ret0
}

func (mr *MockDrsClientMockRecorder) New(method, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockDrsClient)(nil).New), method, url)
}

func (m *MockDrsClient) WithProject(projectId string) drs.Client {
    return m
}

func (m *MockDrsClient) WithOrganization(organization string) drs.Client {
    return m
}

func (m *MockDrsClient) WithBucket(bucketName string) drs.Client {
    return m
}

func (m *MockDrsClient) GetProjectId() string { return "" }
func (m *MockDrsClient) GetBucketName() string { return "" }
func (m *MockDrsClient) GetOrganization() string { return "" }
func (m *MockDrsClient) RegisterFile(ctx context.Context, oid, path string) (*drs.DRSObject, error) { return nil, nil }
func (m *MockDrsClient) AddURL(ctx context.Context, blobURL, sha256 string, opts ...drs.AddURLOption) (*drs.DRSObject, error) { return nil, nil }
func (m *MockDrsClient) ListObjectsByProject(ctx context.Context, projectId string) (chan drs.DRSObjectResult, error) { return nil, nil }
func (m *MockDrsClient) GetProjectSample(ctx context.Context, projectId string, limit int) ([]drs.DRSObject, error) { return nil, nil }
func (m *MockDrsClient) DeleteRecordsByProject(ctx context.Context, projectId string) error { return nil }
func (m *MockDrsClient) BuildDrsObj(fileName string, checksum string, size int64, drsId string) (*drs.DRSObject, error) { return nil, nil }
func (m *MockDrsClient) DownloadFile(ctx context.Context, oid, destPath string) error { return nil }
