// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/indexd (interfaces: IndexdInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_indexd.go -package=mocks github.com/calypr/data-client/indexd IndexdInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	indexd "github.com/calypr/data-client/indexd"
	drs "github.com/calypr/data-client/indexd/drs"
	request "github.com/calypr/data-client/request"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexdInterface is a mock of IndexdInterface interface.
type MockIndexdInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIndexdInterfaceMockRecorder
	isgomock struct{}
}

// MockIndexdInterfaceMockRecorder is the mock recorder for MockIndexdInterface.
type MockIndexdInterfaceMockRecorder struct {
	mock *MockIndexdInterface
}

// NewMockIndexdInterface creates a new mock instance.
func NewMockIndexdInterface(ctrl *gomock.Controller) *MockIndexdInterface {
	mock := &MockIndexdInterface{ctrl: ctrl}
	mock.recorder = &MockIndexdInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexdInterface) EXPECT() *MockIndexdInterfaceMockRecorder {
	return m.recorder
}

// DeleteIndexdRecord mocks base method.
func (m *MockIndexdInterface) DeleteIndexdRecord(ctx context.Context, did string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndexdRecord", ctx, did)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndexdRecord indicates an expected call of DeleteIndexdRecord.
func (mr *MockIndexdInterfaceMockRecorder) DeleteIndexdRecord(ctx, did any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndexdRecord", reflect.TypeOf((*MockIndexdInterface)(nil).DeleteIndexdRecord), ctx, did)
}

// DeleteRecordByHash mocks base method.
func (m *MockIndexdInterface) DeleteRecordByHash(ctx context.Context, hashValue, projectId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordByHash", ctx, hashValue, projectId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordByHash indicates an expected call of DeleteRecordByHash.
func (mr *MockIndexdInterfaceMockRecorder) DeleteRecordByHash(ctx, hashValue, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordByHash", reflect.TypeOf((*MockIndexdInterface)(nil).DeleteRecordByHash), ctx, hashValue, projectId)
}

// DeleteRecordsByProject mocks base method.
func (m *MockIndexdInterface) DeleteRecordsByProject(ctx context.Context, projectId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordsByProject", ctx, projectId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordsByProject indicates an expected call of DeleteRecordsByProject.
func (mr *MockIndexdInterfaceMockRecorder) DeleteRecordsByProject(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordsByProject", reflect.TypeOf((*MockIndexdInterface)(nil).DeleteRecordsByProject), ctx, projectId)
}

// Do mocks base method.
func (m *MockIndexdInterface) Do(ctx context.Context, req *request.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockIndexdInterfaceMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockIndexdInterface)(nil).Do), ctx, req)
}

// GetDownloadURL mocks base method.
func (m *MockIndexdInterface) GetDownloadURL(ctx context.Context, did, accessType string) (*drs.AccessURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadURL", ctx, did, accessType)
	ret0, _ := ret[0].(*drs.AccessURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadURL indicates an expected call of GetDownloadURL.
func (mr *MockIndexdInterfaceMockRecorder) GetDownloadURL(ctx, did, accessType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadURL", reflect.TypeOf((*MockIndexdInterface)(nil).GetDownloadURL), ctx, did, accessType)
}

// GetObject mocks base method.
func (m *MockIndexdInterface) GetObject(ctx context.Context, id string) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, id)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockIndexdInterfaceMockRecorder) GetObject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockIndexdInterface)(nil).GetObject), ctx, id)
}

// GetObjectByHash mocks base method.
func (m *MockIndexdInterface) GetObjectByHash(ctx context.Context, hashType, hashValue string) ([]drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectByHash", ctx, hashType, hashValue)
	ret0, _ := ret[0].([]drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectByHash indicates an expected call of GetObjectByHash.
func (mr *MockIndexdInterfaceMockRecorder) GetObjectByHash(ctx, hashType, hashValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectByHash", reflect.TypeOf((*MockIndexdInterface)(nil).GetObjectByHash), ctx, hashType, hashValue)
}

// GetProjectSample mocks base method.
func (m *MockIndexdInterface) GetProjectSample(ctx context.Context, projectId string, limit int) ([]drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSample", ctx, projectId, limit)
	ret0, _ := ret[0].([]drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSample indicates an expected call of GetProjectSample.
func (mr *MockIndexdInterfaceMockRecorder) GetProjectSample(ctx, projectId, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSample", reflect.TypeOf((*MockIndexdInterface)(nil).GetProjectSample), ctx, projectId, limit)
}

// ListObjects mocks base method.
func (m *MockIndexdInterface) ListObjects(ctx context.Context) (chan drs.DRSObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx)
	ret0, _ := ret[0].(chan drs.DRSObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockIndexdInterfaceMockRecorder) ListObjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockIndexdInterface)(nil).ListObjects), ctx)
}

// ListObjectsByProject mocks base method.
func (m *MockIndexdInterface) ListObjectsByProject(ctx context.Context, projectId string) (chan drs.DRSObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByProject", ctx, projectId)
	ret0, _ := ret[0].(chan drs.DRSObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByProject indicates an expected call of ListObjectsByProject.
func (mr *MockIndexdInterfaceMockRecorder) ListObjectsByProject(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByProject", reflect.TypeOf((*MockIndexdInterface)(nil).ListObjectsByProject), ctx, projectId)
}

// New mocks base method.
func (m *MockIndexdInterface) New(method, url string) *request.RequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", method, url)
	ret0, _ := ret[0].(*request.RequestBuilder)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockIndexdInterfaceMockRecorder) New(method, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIndexdInterface)(nil).New), method, url)
}

// RegisterIndexdRecord mocks base method.
func (m *MockIndexdInterface) RegisterIndexdRecord(ctx context.Context, indexdObj *indexd.IndexdRecord) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterIndexdRecord", ctx, indexdObj)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterIndexdRecord indicates an expected call of RegisterIndexdRecord.
func (mr *MockIndexdInterfaceMockRecorder) RegisterIndexdRecord(ctx, indexdObj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterIndexdRecord", reflect.TypeOf((*MockIndexdInterface)(nil).RegisterIndexdRecord), ctx, indexdObj)
}

// RegisterRecord mocks base method.
func (m *MockIndexdInterface) RegisterRecord(ctx context.Context, record *drs.DRSObject) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterRecord", ctx, record)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRecord indicates an expected call of RegisterRecord.
func (mr *MockIndexdInterfaceMockRecorder) RegisterRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRecord", reflect.TypeOf((*MockIndexdInterface)(nil).RegisterRecord), ctx, record)
}

// UpdateRecord mocks base method.
func (m *MockIndexdInterface) UpdateRecord(ctx context.Context, updateInfo *drs.DRSObject, did string) (*drs.DRSObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecord", ctx, updateInfo, did)
	ret0, _ := ret[0].(*drs.DRSObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecord indicates an expected call of UpdateRecord.
func (mr *MockIndexdInterfaceMockRecorder) UpdateRecord(ctx, updateInfo, did any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecord", reflect.TypeOf((*MockIndexdInterface)(nil).UpdateRecord), ctx, updateInfo, did)
}
