// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/fence (interfaces: FenceInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_fence.go -package=mocks github.com/calypr/data-client/fence FenceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	fence "github.com/calypr/data-client/fence"
	request "github.com/calypr/data-client/request"
	gomock "go.uber.org/mock/gomock"
)

// MockFenceInterface is a mock of FenceInterface interface.
type MockFenceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFenceInterfaceMockRecorder
	isgomock struct{}
}

// MockFenceInterfaceMockRecorder is the mock recorder for MockFenceInterface.
type MockFenceInterfaceMockRecorder struct {
	mock *MockFenceInterface
}

// NewMockFenceInterface creates a new mock instance.
func NewMockFenceInterface(ctrl *gomock.Controller) *MockFenceInterface {
	mock := &MockFenceInterface{ctrl: ctrl}
	mock.recorder = &MockFenceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFenceInterface) EXPECT() *MockFenceInterfaceMockRecorder {
	return m.recorder
}

// CheckForShepherdAPI mocks base method.
func (m *MockFenceInterface) CheckForShepherdAPI(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForShepherdAPI", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckForShepherdAPI indicates an expected call of CheckForShepherdAPI.
func (mr *MockFenceInterfaceMockRecorder) CheckForShepherdAPI(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForShepherdAPI", reflect.TypeOf((*MockFenceInterface)(nil).CheckForShepherdAPI), ctx)
}

// CheckPrivileges mocks base method.
func (m *MockFenceInterface) CheckPrivileges(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPrivileges", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPrivileges indicates an expected call of CheckPrivileges.
func (mr *MockFenceInterfaceMockRecorder) CheckPrivileges(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPrivileges", reflect.TypeOf((*MockFenceInterface)(nil).CheckPrivileges), ctx)
}

// CompleteMultipartUpload mocks base method.
func (m *MockFenceInterface) CompleteMultipartUpload(ctx context.Context, key, uploadID string, parts []fence.MultipartPart, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, key, uploadID, parts, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockFenceInterfaceMockRecorder) CompleteMultipartUpload(ctx, key, uploadID, parts, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockFenceInterface)(nil).CompleteMultipartUpload), ctx, key, uploadID, parts, bucket)
}

// DeleteRecord mocks base method.
func (m *MockFenceInterface) DeleteRecord(ctx context.Context, guid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", ctx, guid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockFenceInterfaceMockRecorder) DeleteRecord(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockFenceInterface)(nil).DeleteRecord), ctx, guid)
}

// Do mocks base method.
func (m *MockFenceInterface) Do(ctx context.Context, req *request.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockFenceInterfaceMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockFenceInterface)(nil).Do), ctx, req)
}

// GenerateMultipartPresignedURL mocks base method.
func (m *MockFenceInterface) GenerateMultipartPresignedURL(ctx context.Context, key, uploadID string, partNumber int, bucket string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMultipartPresignedURL", ctx, key, uploadID, partNumber, bucket)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMultipartPresignedURL indicates an expected call of GenerateMultipartPresignedURL.
func (mr *MockFenceInterfaceMockRecorder) GenerateMultipartPresignedURL(ctx, key, uploadID, partNumber, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMultipartPresignedURL", reflect.TypeOf((*MockFenceInterface)(nil).GenerateMultipartPresignedURL), ctx, key, uploadID, partNumber, bucket)
}

// GetBucketDetails mocks base method.
func (m *MockFenceInterface) GetBucketDetails(ctx context.Context, bucket string) (*fence.S3Bucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketDetails", ctx, bucket)
	ret0, _ := ret[0].(*fence.S3Bucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBucketDetails indicates an expected call of GetBucketDetails.
func (mr *MockFenceInterfaceMockRecorder) GetBucketDetails(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketDetails", reflect.TypeOf((*MockFenceInterface)(nil).GetBucketDetails), ctx, bucket)
}

// GetDownloadPresignedUrl mocks base method.
func (m *MockFenceInterface) GetDownloadPresignedUrl(ctx context.Context, guid, protocolText string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadPresignedUrl", ctx, guid, protocolText)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadPresignedUrl indicates an expected call of GetDownloadPresignedUrl.
func (mr *MockFenceInterfaceMockRecorder) GetDownloadPresignedUrl(ctx, guid, protocolText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadPresignedUrl", reflect.TypeOf((*MockFenceInterface)(nil).GetDownloadPresignedUrl), ctx, guid, protocolText)
}

// GetUploadPresignedUrl mocks base method.
func (m *MockFenceInterface) GetUploadPresignedUrl(ctx context.Context, guid, filename, bucket string) (fence.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUploadPresignedUrl", ctx, guid, filename, bucket)
	ret0, _ := ret[0].(fence.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUploadPresignedUrl indicates an expected call of GetUploadPresignedUrl.
func (mr *MockFenceInterfaceMockRecorder) GetUploadPresignedUrl(ctx, guid, filename, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUploadPresignedUrl", reflect.TypeOf((*MockFenceInterface)(nil).GetUploadPresignedUrl), ctx, guid, filename, bucket)
}

// InitMultipartUpload mocks base method.
func (m *MockFenceInterface) InitMultipartUpload(ctx context.Context, filename, bucket, guid string) (fence.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitMultipartUpload", ctx, filename, bucket, guid)
	ret0, _ := ret[0].(fence.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitMultipartUpload indicates an expected call of InitMultipartUpload.
func (mr *MockFenceInterfaceMockRecorder) InitMultipartUpload(ctx, filename, bucket, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitMultipartUpload", reflect.TypeOf((*MockFenceInterface)(nil).InitMultipartUpload), ctx, filename, bucket, guid)
}

// InitUpload mocks base method.
func (m *MockFenceInterface) InitUpload(ctx context.Context, filename, bucket, guid string) (fence.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitUpload", ctx, filename, bucket, guid)
	ret0, _ := ret[0].(fence.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitUpload indicates an expected call of InitUpload.
func (mr *MockFenceInterfaceMockRecorder) InitUpload(ctx, filename, bucket, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUpload", reflect.TypeOf((*MockFenceInterface)(nil).InitUpload), ctx, filename, bucket, guid)
}

// New mocks base method.
func (m *MockFenceInterface) New(method, url string) *request.RequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", method, url)
	ret0, _ := ret[0].(*request.RequestBuilder)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockFenceInterfaceMockRecorder) New(method, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFenceInterface)(nil).New), method, url)
}

// NewAccessToken mocks base method.
func (m *MockFenceInterface) NewAccessToken(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAccessToken", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAccessToken indicates an expected call of NewAccessToken.
func (mr *MockFenceInterfaceMockRecorder) NewAccessToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAccessToken", reflect.TypeOf((*MockFenceInterface)(nil).NewAccessToken), ctx)
}

// ParseFenceURLResponse mocks base method.
func (m *MockFenceInterface) ParseFenceURLResponse(resp *http.Response) (fence.FenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFenceURLResponse", resp)
	ret0, _ := ret[0].(fence.FenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFenceURLResponse indicates an expected call of ParseFenceURLResponse.
func (mr *MockFenceInterfaceMockRecorder) ParseFenceURLResponse(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFenceURLResponse", reflect.TypeOf((*MockFenceInterface)(nil).ParseFenceURLResponse), resp)
}

// RefreshToken mocks base method.
func (m *MockFenceInterface) RefreshToken(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockFenceInterfaceMockRecorder) RefreshToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockFenceInterface)(nil).RefreshToken), ctx)
}

// UserPing mocks base method.
func (m *MockFenceInterface) UserPing(ctx context.Context) (*fence.PingResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserPing", ctx)
	ret0, _ := ret[0].(*fence.PingResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserPing indicates an expected call of UserPing.
func (mr *MockFenceInterfaceMockRecorder) UserPing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserPing", reflect.TypeOf((*MockFenceInterface)(nil).UserPing), ctx)
}
