// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/data-client/g3client (interfaces: Gen3Interface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_gen3interface.go -package=mocks github.com/calypr/data-client/g3client Gen3Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	conf "github.com/calypr/data-client/conf"
	fence "github.com/calypr/data-client/fence"
	indexd "github.com/calypr/data-client/indexd"
	logs "github.com/calypr/data-client/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockGen3Interface is a mock of Gen3Interface interface.
type MockGen3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockGen3InterfaceMockRecorder
	isgomock struct{}
}

// MockGen3InterfaceMockRecorder is the mock recorder for MockGen3Interface.
type MockGen3InterfaceMockRecorder struct {
	mock *MockGen3Interface
}

// NewMockGen3Interface creates a new mock instance.
func NewMockGen3Interface(ctrl *gomock.Controller) *MockGen3Interface {
	mock := &MockGen3Interface{ctrl: ctrl}
	mock.recorder = &MockGen3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGen3Interface) EXPECT() *MockGen3InterfaceMockRecorder {
	return m.recorder
}

// ExportCredential mocks base method.
func (m *MockGen3Interface) ExportCredential(ctx context.Context, cred *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportCredential indicates an expected call of ExportCredential.
func (mr *MockGen3InterfaceMockRecorder) ExportCredential(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCredential", reflect.TypeOf((*MockGen3Interface)(nil).ExportCredential), ctx, cred)
}

// Fence mocks base method.
func (m *MockGen3Interface) Fence() fence.FenceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fence")
	ret0, _ := ret[0].(fence.FenceInterface)
	return ret0
}

// Fence indicates an expected call of Fence.
func (mr *MockGen3InterfaceMockRecorder) Fence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fence", reflect.TypeOf((*MockGen3Interface)(nil).Fence))
}

// GetCredential mocks base method.
func (m *MockGen3Interface) GetCredential() *conf.Credential {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential")
	ret0, _ := ret[0].(*conf.Credential)
	return ret0
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockGen3InterfaceMockRecorder) GetCredential() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockGen3Interface)(nil).GetCredential))
}

// Indexd mocks base method.
func (m *MockGen3Interface) Indexd() indexd.IndexdInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indexd")
	ret0, _ := ret[0].(indexd.IndexdInterface)
	return ret0
}

// Indexd indicates an expected call of Indexd.
func (mr *MockGen3InterfaceMockRecorder) Indexd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexd", reflect.TypeOf((*MockGen3Interface)(nil).Indexd))
}

// Logger mocks base method.
func (m *MockGen3Interface) Logger() *logs.Gen3Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*logs.Gen3Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockGen3InterfaceMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockGen3Interface)(nil).Logger))
}
