// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/calypr-cli/g3client (interfaces: Gen3Interface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_gen3interface.go -package=mocks github.com/calypr/calypr-cli/g3client Gen3Interface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	fence "github.com/calypr/calypr-cli/fence"
	g3client "github.com/calypr/calypr-cli/g3client"
	gecko "github.com/calypr/calypr-cli/gecko"
	logs "github.com/calypr/calypr-cli/logs"
	request "github.com/calypr/calypr-cli/request"
	requestor "github.com/calypr/calypr-cli/requestor"
	sower "github.com/calypr/calypr-cli/sower"
	syconfig "github.com/calypr/syfon/client/config"
	gomock "go.uber.org/mock/gomock"
)

// MockGen3Interface is a mock of Gen3Interface interface.
type MockGen3Interface struct {
	ctrl     *gomock.Controller
	recorder *MockGen3InterfaceMockRecorder
	isgomock struct{}
}

// MockGen3InterfaceMockRecorder is the mock recorder for MockGen3Interface.
type MockGen3InterfaceMockRecorder struct {
	mock *MockGen3Interface
}

// NewMockGen3Interface creates a new mock instance.
func NewMockGen3Interface(ctrl *gomock.Controller) *MockGen3Interface {
	mock := &MockGen3Interface{ctrl: ctrl}
	mock.recorder = &MockGen3InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGen3Interface) EXPECT() *MockGen3InterfaceMockRecorder {
	return m.recorder
}

// Credentials mocks base method.
func (m *MockGen3Interface) Credentials() syconfig.CredentialManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credentials")
	ret0, _ := ret[0].(syconfig.CredentialManager)
	return ret0
}

// Credentials indicates an expected call of Credentials.
func (mr *MockGen3InterfaceMockRecorder) Credentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credentials", reflect.TypeOf((*MockGen3Interface)(nil).Credentials))
}

// SyfonClient mocks base method.
func (m *MockGen3Interface) SyfonClient() g3client.SyfonClientInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyfonClient")
	ret0, _ := ret[0].(g3client.SyfonClientInterface)
	return ret0
}

// SyfonClient indicates an expected call of SyfonClient.
func (mr *MockGen3InterfaceMockRecorder) SyfonClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyfonClient", reflect.TypeOf((*MockGen3Interface)(nil).SyfonClient))
}

// Do mocks base method.
func (m *MockGen3Interface) Do(ctx context.Context, req *request.RequestBuilder) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGen3InterfaceMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGen3Interface)(nil).Do), ctx, req)
}

// FenceClient mocks base method.
func (m *MockGen3Interface) FenceClient() fence.FenceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FenceClient")
	ret0, _ := ret[0].(fence.FenceInterface)
	return ret0
}

// FenceClient indicates an expected call of FenceClient.
func (mr *MockGen3InterfaceMockRecorder) FenceClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FenceClient", reflect.TypeOf((*MockGen3Interface)(nil).FenceClient))
}

// GeckoClient mocks base method.
func (m *MockGen3Interface) GeckoClient() gecko.GeckoInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeckoClient")
	ret0, _ := ret[0].(gecko.GeckoInterface)
	return ret0
}

// GeckoClient indicates an expected call of GeckoClient.
func (mr *MockGen3InterfaceMockRecorder) GeckoClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeckoClient", reflect.TypeOf((*MockGen3Interface)(nil).GeckoClient))
}

// Logger mocks base method.
func (m *MockGen3Interface) Logger() *logs.Gen3Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*logs.Gen3Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockGen3InterfaceMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockGen3Interface)(nil).Logger))
}

// New mocks base method.
func (m *MockGen3Interface) New(method, url string) *request.RequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", method, url)
	ret0, _ := ret[0].(*request.RequestBuilder)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockGen3InterfaceMockRecorder) New(method, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGen3Interface)(nil).New), method, url)
}

// RequestorClient mocks base method.
func (m *MockGen3Interface) RequestorClient() requestor.RequestorInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestorClient")
	ret0, _ := ret[0].(requestor.RequestorInterface)
	return ret0
}

// RequestorClient indicates an expected call of RequestorClient.
func (mr *MockGen3InterfaceMockRecorder) RequestorClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestorClient", reflect.TypeOf((*MockGen3Interface)(nil).RequestorClient))
}

// SowerClient mocks base method.
func (m *MockGen3Interface) SowerClient() sower.SowerInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SowerClient")
	ret0, _ := ret[0].(sower.SowerInterface)
	return ret0
}

// SowerClient indicates an expected call of SowerClient.
func (mr *MockGen3InterfaceMockRecorder) SowerClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SowerClient", reflect.TypeOf((*MockGen3Interface)(nil).SowerClient))
}
